"""Shared cosmetic shop catalogue for the Puzzle + Guess bots."""

SHOP_BUILD = "cosmetics-shop-v1-2026-09-05"

BADGE_BOX_COST = 50.0
BOARD_COST = 100.0
PIECE_COST = 100.0
SURVIVAL_HEART_COST = 100.0
COLOR_COST = 500.0

BADGE_RARITY_WEIGHTS = {
    "legendary": 1,
    "epic": 4,
    "rare": 10,
    "uncommon": 20,
    "common": 30,
    "basic": 35,
}

# Legendary is intentionally reserved for Shark's own Discord server emotes.
BADGE_POOLS = {
    "legendary": [
        "<:BIGBRAIN:1525486567219531777>",
        "<:BITS:1525487690554933378>",
        "<:BLUNDER:1525486089744154684>",
        "<:BRILLIANT:1525486133172240566>",
        "<:BRILLIANTBLUNDER:1525486423593975869>",
        "<:CONFUSED:1525486915103621150>",
        "<:COOKING:1525487725954728156>",
        "<:CRY:1525487422681518200>",
        "<:DANCE:1525487158729769010>",
        "<:DETECTIVE:1525486511620096100>",
        "<:DUBOVITALIAN:1525487113573896302>",
        "<:EZ:1525486209881735189>",
        "<:FACEPALM:1525486622873882644>",
        "<:GG:1525487789095784692>",
        "<:GUESSING:1525487842204057620>",
        "<:HEART:1525487524301242489>",
        "<:HYPE:1525487466654728242>",
        "<:INTERESTING:1525486348423659553>",
        "<:LAUGHING:1525487355031457864>",
        "<:PANIC:1525487257157500978>",
        "<:SCARED:1525487015724974172>",
        "<:SH4RKMATE:1525488071158665268>",
        "<:SLEEP:1525486795855495208>",
        "<:STOP:1525487597110165504>",
        "<:SUBSCRIBE:1525487952187228281>",
        "<:WAVE:1525487900924575784>",
    ],
    "epic": "👑 🐐 🦄 🐲 🐦‍🔥".split(),
    "rare": "⭐ 💎 🔥 🌈 ⚡ 💀 ☠️ 🤖 🗿 🚀 🛸 🔱 👾 🦈 🧙 🧬 🦋 🦕 🦉".split(),
    "uncommon": """
🏆 🥇 🏅 🎖️ ✨ ☄️ 🌌 🪐 🔮 🪄 🥷 🧛 👻 👽 🦁 🐯 🐺 🦅 🦂 🐍 🦇 🦖 🦚
🦍 🦧 🐆 🐊 🐋 🐬 🐙 🦑 🦞 🦀 🐈‍⬛ 🐻‍❄️ ♟️ 🎯 🎰 🕹️ 🎮 🎲 🧩 ⚔️ 🛡️ 🏹 🗡️ 💣 🧨
⛓️ 🧲 🔑 🗝️ 🔏 👀 👁️
""".split(),
    "common": """
🧠 ❤️ 🧡 💛 💚 💙 💜 🖤 🤍 🤎 🩷 🩵 🩶 💔 💕 💞 💓 💗 💝 💘
☀️ 🌕 🌑 🌙 ☁️ 🌧️ 🌨️ 🌩️ ❄️ ☂️ 🌊 🌀 🌫️ 🌪️ 🌹 🌻 🌷 🌺 🌸 🪷 🍀 🌵 🌴 🌲 🌳 🍄
🦊 🦝 🐼 🐨 🐻 🐩 🐈 🐕 🐇 🐹 🐁 🐀 🦔 🦡 🦦 🦫 🦥 🦘 🐪 🦙 🦒 🐘 🦏 🦛
🦜 🦩 🦢 🐧 🦆 🐔 🐓 🦃 🐝 🐞 🪲 🐛 🐜 🕷️ 🐌 🪱 🐟 🐠 🐡 🦐 🦭 🐢 🐸
""".split(),
    "basic": """
🍎 🍏 🍐 🍊 🍋 🍋‍🟩 🍌 🍉 🍇 🍓 🫐 🍈 🍒 🍑 🥭 🍍 🥝 🍅 🥑 🫒 🥥
🥕 🌽 🌶️ 🫑 🥒 🥬 🥦 🧄 🧅 🥔 🍠 🫘 🌰 🥜 🍞 🥐 🥖 🫓 🥨 🥯 🥞 🧇 🧀
🍗 🍖 🌭 🍔 🍟 🍕 🥪 🥙 🧆 🌮 🌯 🫔 🥗 🥘 🫕 🥫 🍝 🍜 🍲 🍛 🍣 🍱 🥟 🦪 🍤 🍙 🍚 🍘 🍥
🍦 🍧 🍨 🍩 🍪 🎂 🍰 🧁 🥧 🍫 🍬 🍭 🍮 🍯 ☕ 🍵 🫖 🥤 🧋 🧃 🥛
⌚ 📱 💻 ⌨️ 🖥️ 🖨️ 🖱️ 💽 💾 💿 📀 📷 📸 📹 🎥 📺 📻 🎙️ 🎚️ 🎛️ ☎️ 📞 📟 📠
🔋 🪫 🔌 💡 🔦 🕯️ 📚 📖 📝 ✏️ 🖊️ 🖋️ 🖌️ 🖍️ 📌 📍 📎 🖇️ 📏 📐 ✂️ 📦 📫 📬 ✉️ 💌
🧹 🧺 🧻 🪣 🧼 🫧 🧽 🪑 🛏️ 🛋️ 🚪 🪞 🪟 ⏰ ⌛ ⏳ ⏱️ ⏲️ 🔧 🔨 ⚒️ 🛠️ ⛏️ 🪚 🔩 ⚙️ 🧱 🪨 🪵
⚽ 🏀 🏈 ⚾ 🥎 🎾 🏐 🏉 🥏 🎱 🪀 🏓 🏸 🏒 🏑 🥍 🏏 ⛳ 🪁 🛝 🛼 🛹 ⛸️ 🎿 🎣 🤿 🥊 🥋
🎨 🧵 🪡 🧶 🎭 🎤 🎧 🎷 🎸 🎹 🥁 🎺 🎻
🚗 🚕 🚙 🚌 🚎 🏎️ 🚓 🚑 🚒 🚐 🛻 🚚 🚛 🚜 🏍️ 🛵 🚲 🛴 🚂 🚆 🚇 🚊 🚉 ✈️ 🛫 🛬 🚁 ⛵ 🚤 🛥️ 🚢
✅ ❌ ❗ ❓ ⭕ ❎ ➕ ➖ ➗ ✖️ ⬆️ ⬇️ ⬅️ ➡️ ↗️ ↘️ ↙️ ↖️
🔴 🟠 🟡 🟢 🔵 🟣 ⚫ ⚪ 🟤 🟥 🟧 🟨 🟩 🟦 🟪 ⬛ ⬜ 🟫 🔺 🔻 🔸 🔹 🔶 🔷
♠️ ♥️ ♦️ ♣️ 🔔 🔕 📣 📢 💬 💭 🗯️ ✔️ ☑️
😀 😃 😄 😁 😆 😅 😂 🤣 🙂 🙃 😉 😊 😇 🥰 😍 🤩 😘 😋 😛 😜 🤪 🤨 🧐 🤓 😎 🥸
😏 😒 😞 😔 😟 😕 🙁 ☹️ 😣 😖 😫 😩 🥺 😢 😭 😤 😠 😡 🤬 🤯 😳 🥵 🥶 😱 😨 😰 😥
🤔 🫡 🤭 🫢 🤫 😶 😐 😑 🥱 😴 🤤
👍 👎 👌 ✌️ 🤞 🤟 🤘 🤙 👈 👉 👆 👇 ☝️ ✋ 🤚 🖐️ 🖖 👋 👏 🙌 🫶 🤝 💪 🦾 🙏 ✍️ 👂 👃 🦶 🦵
""".split(),
}

RARITY_LABELS = {
    "legendary": "Legendary",
    "epic": "Epic",
    "rare": "Rare",
    "uncommon": "Uncommon",
    "common": "Common",
    "basic": "Basic",
}

# 50 board themes. Only square colors are overridden; coordinates/pieces keep
# the proven python-chess defaults for maximum readability.
BOARD_THEMES = {'classic': ('#f0d9b5', '#b58863'),
 'blue': ('#dbeafe', '#4776a8'),
 'red': ('#f7d7d7', '#a94b4b'),
 'green': ('#e0efd4', '#6b8f5a'),
 'purple': ('#eadcf4', '#77588f'),
 'ocean': ('#d5f3f6', '#2f7888'),
 'midnight': ('#b9c4d0', '#253247'),
 'forest': ('#dfe8cf', '#4f6b45'),
 'rose': ('#f6dce5', '#a85f79'),
 'gold': ('#f7e8aa', '#9c7729'),
 'silver': ('#eceff1', '#7b8790'),
 'ice': ('#e5f8ff', '#69a6c5'),
 'lava': ('#ffd7b5', '#8f2f1f'),
 'neon': ('#d8ffb8', '#4c3c78'),
 'cyber': ('#c9f7ef', '#37516d'),
 'galaxy': ('#d7d0ef', '#39305f'),
 'sunset': ('#ffd9c2', '#9a5570'),
 'candy': ('#ffe2f2', '#70b9c7'),
 'mint': ('#daf5e7', '#57977b'),
 'coffee': ('#ead8c4', '#76533d'),
 'wood': ('#e6c99f', '#8c623f'),
 'marble': ('#f2f1ed', '#90979b'),
 'slate': ('#d7dde1', '#53606b'),
 'royal': ('#e1ddff', '#4b3c94'),
 'emerald': ('#d8f1df', '#287650'),
 'ruby': ('#f6dbdf', '#8d3244'),
 'sapphire': ('#dae4f7', '#2d5b96'),
 'amethyst': ('#eadcf5', '#74508d'),
 'arctic': ('#eefcff', '#83aebd'),
 'desert': ('#f4e0b8', '#a67845'),
 'jungle': ('#d7e7c0', '#446b3a'),
 'volcano': ('#f3c8b2', '#63342d'),
 'storm': ('#d9dde6', '#4c5367'),
 'peach': ('#ffe4cf', '#ba7862'),
 'lavender': ('#eee2f7', '#8d73a3'),
 'aqua': ('#d7f6f4', '#418d91'),
 'coral': ('#f9ded7', '#bc6a5e'),
 'lime': ('#e7f3c9', '#75934a'),
 'mono': ('#eeeeee', '#777777'),
 'graphite': ('#d4d4d4', '#4b4b4b'),
 'chesscom': ('#eeeed2', '#769656'),
 'lichess': ('#f0d9b5', '#b58863'),
 'retro': ('#f1d7a5', '#8b6a45'),
 'arcade': ('#dff7d1', '#5d4b88'),
 'halloween': ('#f3d29c', '#57394f'),
 'christmas': ('#f0e7d0', '#3f7553'),
 'spring': ('#ecf2cb', '#77a66b'),
 'autumn': ('#f0d1a8', '#8d5d38'),
 'nether': ('#e7c7c7', '#5b2d39'),
 'void': ('#cbc7d6', '#272331'),
 'teal': ('#d7f2ef', '#3f7f79'),
 'navy': ('#d9e2ef', '#30486f'),
 'sky': ('#e1f3ff', '#69a7cc'),
 'cobalt': ('#dce6f7', '#315f9e'),
 'indigo': ('#e4e0f4', '#4d4c91'),
 'violet': ('#eee1f4', '#855aa1'),
 'magenta': ('#f5ddea', '#9f4777'),
 'berry': ('#f3d9e3', '#8f435f'),
 'cherry': ('#f7d9dc', '#a54550'),
 'salmon': ('#f8dfd8', '#b86f61'),
 'amber': ('#f7e6bd', '#ad7b32'),
 'bronze': ('#ead5b7', '#88613a'),
 'copper': ('#f0d2bd', '#995c42'),
 'sand': ('#f2e5c9', '#aa8d5a'),
 'cream': ('#fff3d7', '#a78c63'),
 'olive': ('#eaebc9', '#7f834c'),
 'moss': ('#e0e8c7', '#667a45'),
 'sage': ('#e7ecd9', '#7b8e69'),
 'pine': ('#d9e7d9', '#3e684d'),
 'bamboo': ('#ebefcf', '#81934f'),
 'seafoam': ('#dbf3e7', '#4f9481'),
 'lagoon': ('#d6eff0', '#3f8290'),
 'tropical': ('#ddf1dd', '#39826a'),
 'frost': ('#effaff', '#75a7bb'),
 'glacier': ('#e5f2fb', '#668ca8'),
 'aurora': ('#e6f2e2', '#5f7a88'),
 'dusk': ('#e8dce5', '#72596f'),
 'twilight': ('#dfdbe8', '#514f72'),
 'night': ('#cfd7e2', '#283546'),
 'eclipse': ('#d5d2dc', '#38343f'),
 'carbon': ('#d7d7d7', '#3a3a3a'),
 'ash': ('#e5e5e2', '#6f7476'),
 'smoke': ('#e0e3e6', '#687078'),
 'paper': ('#faf7eb', '#9c927d'),
 'ivory': ('#fff8e7', '#a99a78'),
 'sandstone': ('#f1dfc5', '#9b7854'),
 'clay': ('#efd3c5', '#9f6656'),
 'terracotta': ('#f0d1c0', '#985c45'),
 'mocha': ('#e7d4c4', '#72503e'),
 'espresso': ('#ddcfca', '#4e3b36'),
 'plum': ('#eadce7', '#704e69'),
 'grape': ('#e5d9ed', '#684b81'),
 'orchid': ('#f0dff3', '#8e5d99'),
 'blossom': ('#f8e4e9', '#a46a7c'),
 'watermelon': ('#f5dfd9', '#63906a'),
 'lemon': ('#fff4c9', '#aa9846'),
 'kiwi': ('#edf1cd', '#718d4b'),
 'matrix': ('#d9f2d2', '#37644a'),
 'synthwave': ('#ecdaf3', '#4e4f94'),
 'deepsea': ('#d5e7ec', '#285565')}

BOARD_DISPLAY_NAMES = {
    "chesscom": "Chess.com",
    **{name: name.title() for name in BOARD_THEMES if name != "chesscom"},
}

PIECE_SETS = {'classic': {'label': 'Classic', 'shape': 'classic', 'palette': 'classic'},
 'figurine': {'label': 'Figurine',
              'shape': 'figurine',
              'white_fill': '#f7f7f2',
              'black_fill': '#111111',
              'black_stroke': '#1a1a1a',
              'white_stroke': '#f7f7f2'},
 'figurine-gold': {'label': 'Figurine Gold',
                   'shape': 'figurine',
                   'white_fill': '#f5df9a',
                   'black_fill': '#8a5a14',
                   'black_stroke': '#5a3a0d',
                   'white_stroke': '#fff8dc'},
 'figurine-ruby': {'label': 'Figurine Ruby',
                   'shape': 'figurine',
                   'white_fill': '#f7e7e9',
                   'black_fill': '#8b2438',
                   'black_stroke': '#581421',
                   'white_stroke': '#fff8f8'},
 'figurine-emerald': {'label': 'Figurine Emerald',
                      'shape': 'figurine',
                      'white_fill': '#e9f7ef',
                      'black_fill': '#216b48',
                      'black_stroke': '#12402a',
                      'white_stroke': '#f6fff9'},
 'figurine-sapphire': {'label': 'Figurine Sapphire',
                       'shape': 'figurine',
                       'white_fill': '#e8eef9',
                       'black_fill': '#24558d',
                       'black_stroke': '#16345a',
                       'white_stroke': '#f7fbff'},
 'figurine-violet': {'label': 'Figurine Violet',
                     'shape': 'figurine',
                     'white_fill': '#f0e9f7',
                     'black_fill': '#70418e',
                     'black_stroke': '#44245a',
                     'white_stroke': '#fff8ff'},
 'figurine-neon': {'label': 'Figurine Neon',
                   'shape': 'figurine',
                   'white_fill': '#d9ffef',
                   'black_fill': '#1ed760',
                   'black_stroke': '#0b5629',
                   'white_stroke': '#effff6'},
 'figurine-obsidian': {'label': 'Figurine Obsidian',
                       'shape': 'figurine',
                       'white_fill': '#f1f1f1',
                       'black_fill': '#242424',
                       'black_stroke': '#080808',
                       'white_stroke': '#ffffff'},
 'figurine-copper': {'label': 'Figurine Copper',
                     'shape': 'figurine',
                     'white_fill': '#f4dfd0',
                     'black_fill': '#9b5b3d',
                     'black_stroke': '#643421',
                     'white_stroke': '#fff8f2'},
 'figurine-ice': {'label': 'Figurine Ice',
                  'shape': 'figurine',
                  'white_fill': '#eefaff',
                  'black_fill': '#5f91b4',
                  'black_stroke': '#335b78',
                  'white_stroke': '#ffffff'},
 'figurine-rose': {'label': 'Figurine Rose',
                   'shape': 'figurine',
                   'white_fill': '#f9e8ee',
                   'black_fill': '#a94f72',
                   'black_stroke': '#6f2e49',
                   'white_stroke': '#fff8fb'},
 'figurine-aqua': {'label': 'Figurine Aqua',
                   'shape': 'figurine',
                   'white_fill': '#e2f9f7',
                   'black_fill': '#30878a',
                   'black_stroke': '#18575a',
                   'white_stroke': '#f6ffff'},
 'figurine-amber': {'label': 'Figurine Amber',
                    'shape': 'figurine',
                    'white_fill': '#fff0c9',
                    'black_fill': '#a46c18',
                    'black_stroke': '#67420d',
                    'white_stroke': '#fffaf0'},
 'figurine-lime': {'label': 'Figurine Lime',
                   'shape': 'figurine',
                   'white_fill': '#f1f7d8',
                   'black_fill': '#6f8f2f',
                   'black_stroke': '#425817',
                   'white_stroke': '#fbfff0'},
 'figurine-crimson': {'label': 'Figurine Crimson',
                      'shape': 'figurine',
                      'white_fill': '#f8e4e4',
                      'black_fill': '#9f2333',
                      'black_stroke': '#651522',
                      'white_stroke': '#fff7f7'},
 'figurine-silver': {'label': 'Figurine Silver',
                     'shape': 'figurine',
                     'white_fill': '#f3f4f5',
                     'black_fill': '#68747c',
                     'black_stroke': '#394147',
                     'white_stroke': '#ffffff'},
 'monogram': {'label': 'Monogram',
              'shape': 'monogram',
              'white_fill': '#f7f7f2',
              'black_fill': '#111111',
              'black_stroke': '#1a1a1a',
              'white_stroke': '#f7f7f2'},
 'monogram-gold': {'label': 'Monogram Gold',
                   'shape': 'monogram',
                   'white_fill': '#f5df9a',
                   'black_fill': '#8a5a14',
                   'black_stroke': '#5a3a0d',
                   'white_stroke': '#fff8dc'},
 'monogram-ruby': {'label': 'Monogram Ruby',
                   'shape': 'monogram',
                   'white_fill': '#f7e7e9',
                   'black_fill': '#8b2438',
                   'black_stroke': '#581421',
                   'white_stroke': '#fff8f8'},
 'monogram-emerald': {'label': 'Monogram Emerald',
                      'shape': 'monogram',
                      'white_fill': '#e9f7ef',
                      'black_fill': '#216b48',
                      'black_stroke': '#12402a',
                      'white_stroke': '#f6fff9'},
 'monogram-sapphire': {'label': 'Monogram Sapphire',
                       'shape': 'monogram',
                       'white_fill': '#e8eef9',
                       'black_fill': '#24558d',
                       'black_stroke': '#16345a',
                       'white_stroke': '#f7fbff'},
 'monogram-violet': {'label': 'Monogram Violet',
                     'shape': 'monogram',
                     'white_fill': '#f0e9f7',
                     'black_fill': '#70418e',
                     'black_stroke': '#44245a',
                     'white_stroke': '#fff8ff'},
 'monogram-neon': {'label': 'Monogram Neon',
                   'shape': 'monogram',
                   'white_fill': '#d9ffef',
                   'black_fill': '#1ed760',
                   'black_stroke': '#0b5629',
                   'white_stroke': '#effff6'},
 'monogram-obsidian': {'label': 'Monogram Obsidian',
                       'shape': 'monogram',
                       'white_fill': '#f1f1f1',
                       'black_fill': '#242424',
                       'black_stroke': '#080808',
                       'white_stroke': '#ffffff'},
 'monogram-copper': {'label': 'Monogram Copper',
                     'shape': 'monogram',
                     'white_fill': '#f4dfd0',
                     'black_fill': '#9b5b3d',
                     'black_stroke': '#643421',
                     'white_stroke': '#fff8f2'},
 'monogram-ice': {'label': 'Monogram Ice',
                  'shape': 'monogram',
                  'white_fill': '#eefaff',
                  'black_fill': '#5f91b4',
                  'black_stroke': '#335b78',
                  'white_stroke': '#ffffff'},
 'monogram-rose': {'label': 'Monogram Rose',
                   'shape': 'monogram',
                   'white_fill': '#f9e8ee',
                   'black_fill': '#a94f72',
                   'black_stroke': '#6f2e49',
                   'white_stroke': '#fff8fb'},
 'monogram-aqua': {'label': 'Monogram Aqua',
                   'shape': 'monogram',
                   'white_fill': '#e2f9f7',
                   'black_fill': '#30878a',
                   'black_stroke': '#18575a',
                   'white_stroke': '#f6ffff'},
 'monogram-amber': {'label': 'Monogram Amber',
                    'shape': 'monogram',
                    'white_fill': '#fff0c9',
                    'black_fill': '#a46c18',
                    'black_stroke': '#67420d',
                    'white_stroke': '#fffaf0'},
 'monogram-lime': {'label': 'Monogram Lime',
                   'shape': 'monogram',
                   'white_fill': '#f1f7d8',
                   'black_fill': '#6f8f2f',
                   'black_stroke': '#425817',
                   'white_stroke': '#fbfff0'},
 'monogram-crimson': {'label': 'Monogram Crimson',
                      'shape': 'monogram',
                      'white_fill': '#f8e4e4',
                      'black_fill': '#9f2333',
                      'black_stroke': '#651522',
                      'white_stroke': '#fff7f7'},
 'monogram-silver': {'label': 'Monogram Silver',
                     'shape': 'monogram',
                     'white_fill': '#f3f4f5',
                     'black_fill': '#68747c',
                     'black_stroke': '#394147',
                     'white_stroke': '#ffffff'},
 'token': {'label': 'Token',
           'shape': 'token',
           'white_fill': '#f7f7f2',
           'black_fill': '#111111',
           'black_stroke': '#1a1a1a',
           'white_stroke': '#f7f7f2'},
 'token-gold': {'label': 'Token Gold',
                'shape': 'token',
                'white_fill': '#f5df9a',
                'black_fill': '#8a5a14',
                'black_stroke': '#5a3a0d',
                'white_stroke': '#fff8dc'},
 'token-ruby': {'label': 'Token Ruby',
                'shape': 'token',
                'white_fill': '#f7e7e9',
                'black_fill': '#8b2438',
                'black_stroke': '#581421',
                'white_stroke': '#fff8f8'},
 'token-emerald': {'label': 'Token Emerald',
                   'shape': 'token',
                   'white_fill': '#e9f7ef',
                   'black_fill': '#216b48',
                   'black_stroke': '#12402a',
                   'white_stroke': '#f6fff9'},
 'token-sapphire': {'label': 'Token Sapphire',
                    'shape': 'token',
                    'white_fill': '#e8eef9',
                    'black_fill': '#24558d',
                    'black_stroke': '#16345a',
                    'white_stroke': '#f7fbff'},
 'token-violet': {'label': 'Token Violet',
                  'shape': 'token',
                  'white_fill': '#f0e9f7',
                  'black_fill': '#70418e',
                  'black_stroke': '#44245a',
                  'white_stroke': '#fff8ff'},
 'token-neon': {'label': 'Token Neon',
                'shape': 'token',
                'white_fill': '#d9ffef',
                'black_fill': '#1ed760',
                'black_stroke': '#0b5629',
                'white_stroke': '#effff6'},
 'token-obsidian': {'label': 'Token Obsidian',
                    'shape': 'token',
                    'white_fill': '#f1f1f1',
                    'black_fill': '#242424',
                    'black_stroke': '#080808',
                    'white_stroke': '#ffffff'},
 'token-copper': {'label': 'Token Copper',
                  'shape': 'token',
                  'white_fill': '#f4dfd0',
                  'black_fill': '#9b5b3d',
                  'black_stroke': '#643421',
                  'white_stroke': '#fff8f2'},
 'token-ice': {'label': 'Token Ice',
               'shape': 'token',
               'white_fill': '#eefaff',
               'black_fill': '#5f91b4',
               'black_stroke': '#335b78',
               'white_stroke': '#ffffff'},
 'token-rose': {'label': 'Token Rose',
                'shape': 'token',
                'white_fill': '#f9e8ee',
                'black_fill': '#a94f72',
                'black_stroke': '#6f2e49',
                'white_stroke': '#fff8fb'},
 'token-aqua': {'label': 'Token Aqua',
                'shape': 'token',
                'white_fill': '#e2f9f7',
                'black_fill': '#30878a',
                'black_stroke': '#18575a',
                'white_stroke': '#f6ffff'},
 'token-amber': {'label': 'Token Amber',
                 'shape': 'token',
                 'white_fill': '#fff0c9',
                 'black_fill': '#a46c18',
                 'black_stroke': '#67420d',
                 'white_stroke': '#fffaf0'},
 'token-lime': {'label': 'Token Lime',
                'shape': 'token',
                'white_fill': '#f1f7d8',
                'black_fill': '#6f8f2f',
                'black_stroke': '#425817',
                'white_stroke': '#fbfff0'},
 'token-crimson': {'label': 'Token Crimson',
                   'shape': 'token',
                   'white_fill': '#f8e4e4',
                   'black_fill': '#9f2333',
                   'black_stroke': '#651522',
                   'white_stroke': '#fff7f7'},
 'token-silver': {'label': 'Token Silver',
                  'shape': 'token',
                  'white_fill': '#f3f4f5',
                  'black_fill': '#68747c',
                  'black_stroke': '#394147',
                  'white_stroke': '#ffffff'},
 'diamond': {'label': 'Diamond',
             'shape': 'diamond',
             'white_fill': '#f7f7f2',
             'black_fill': '#111111',
             'black_stroke': '#1a1a1a',
             'white_stroke': '#f7f7f2'},
 'diamond-gold': {'label': 'Diamond Gold',
                  'shape': 'diamond',
                  'white_fill': '#f5df9a',
                  'black_fill': '#8a5a14',
                  'black_stroke': '#5a3a0d',
                  'white_stroke': '#fff8dc'},
 'diamond-ruby': {'label': 'Diamond Ruby',
                  'shape': 'diamond',
                  'white_fill': '#f7e7e9',
                  'black_fill': '#8b2438',
                  'black_stroke': '#581421',
                  'white_stroke': '#fff8f8'},
 'diamond-emerald': {'label': 'Diamond Emerald',
                     'shape': 'diamond',
                     'white_fill': '#e9f7ef',
                     'black_fill': '#216b48',
                     'black_stroke': '#12402a',
                     'white_stroke': '#f6fff9'},
 'diamond-sapphire': {'label': 'Diamond Sapphire',
                      'shape': 'diamond',
                      'white_fill': '#e8eef9',
                      'black_fill': '#24558d',
                      'black_stroke': '#16345a',
                      'white_stroke': '#f7fbff'},
 'diamond-violet': {'label': 'Diamond Violet',
                    'shape': 'diamond',
                    'white_fill': '#f0e9f7',
                    'black_fill': '#70418e',
                    'black_stroke': '#44245a',
                    'white_stroke': '#fff8ff'},
 'diamond-neon': {'label': 'Diamond Neon',
                  'shape': 'diamond',
                  'white_fill': '#d9ffef',
                  'black_fill': '#1ed760',
                  'black_stroke': '#0b5629',
                  'white_stroke': '#effff6'},
 'diamond-obsidian': {'label': 'Diamond Obsidian',
                      'shape': 'diamond',
                      'white_fill': '#f1f1f1',
                      'black_fill': '#242424',
                      'black_stroke': '#080808',
                      'white_stroke': '#ffffff'},
 'diamond-copper': {'label': 'Diamond Copper',
                    'shape': 'diamond',
                    'white_fill': '#f4dfd0',
                    'black_fill': '#9b5b3d',
                    'black_stroke': '#643421',
                    'white_stroke': '#fff8f2'},
 'diamond-ice': {'label': 'Diamond Ice',
                 'shape': 'diamond',
                 'white_fill': '#eefaff',
                 'black_fill': '#5f91b4',
                 'black_stroke': '#335b78',
                 'white_stroke': '#ffffff'},
 'diamond-rose': {'label': 'Diamond Rose',
                  'shape': 'diamond',
                  'white_fill': '#f9e8ee',
                  'black_fill': '#a94f72',
                  'black_stroke': '#6f2e49',
                  'white_stroke': '#fff8fb'},
 'diamond-aqua': {'label': 'Diamond Aqua',
                  'shape': 'diamond',
                  'white_fill': '#e2f9f7',
                  'black_fill': '#30878a',
                  'black_stroke': '#18575a',
                  'white_stroke': '#f6ffff'},
 'diamond-amber': {'label': 'Diamond Amber',
                   'shape': 'diamond',
                   'white_fill': '#fff0c9',
                   'black_fill': '#a46c18',
                   'black_stroke': '#67420d',
                   'white_stroke': '#fffaf0'},
 'diamond-lime': {'label': 'Diamond Lime',
                  'shape': 'diamond',
                  'white_fill': '#f1f7d8',
                  'black_fill': '#6f8f2f',
                  'black_stroke': '#425817',
                  'white_stroke': '#fbfff0'},
 'diamond-crimson': {'label': 'Diamond Crimson',
                     'shape': 'diamond',
                     'white_fill': '#f8e4e4',
                     'black_fill': '#9f2333',
                     'black_stroke': '#651522',
                     'white_stroke': '#fff7f7'},
 'diamond-silver': {'label': 'Diamond Silver',
                    'shape': 'diamond',
                    'white_fill': '#f3f4f5',
                    'black_fill': '#68747c',
                    'black_stroke': '#394147',
                    'white_stroke': '#ffffff'},
 'shield': {'label': 'Shield',
            'shape': 'shield',
            'white_fill': '#f7f7f2',
            'black_fill': '#111111',
            'black_stroke': '#1a1a1a',
            'white_stroke': '#f7f7f2'},
 'shield-gold': {'label': 'Shield Gold',
                 'shape': 'shield',
                 'white_fill': '#f5df9a',
                 'black_fill': '#8a5a14',
                 'black_stroke': '#5a3a0d',
                 'white_stroke': '#fff8dc'},
 'shield-ruby': {'label': 'Shield Ruby',
                 'shape': 'shield',
                 'white_fill': '#f7e7e9',
                 'black_fill': '#8b2438',
                 'black_stroke': '#581421',
                 'white_stroke': '#fff8f8'},
 'shield-emerald': {'label': 'Shield Emerald',
                    'shape': 'shield',
                    'white_fill': '#e9f7ef',
                    'black_fill': '#216b48',
                    'black_stroke': '#12402a',
                    'white_stroke': '#f6fff9'},
 'shield-sapphire': {'label': 'Shield Sapphire',
                     'shape': 'shield',
                     'white_fill': '#e8eef9',
                     'black_fill': '#24558d',
                     'black_stroke': '#16345a',
                     'white_stroke': '#f7fbff'},
 'shield-violet': {'label': 'Shield Violet',
                   'shape': 'shield',
                   'white_fill': '#f0e9f7',
                   'black_fill': '#70418e',
                   'black_stroke': '#44245a',
                   'white_stroke': '#fff8ff'},
 'shield-neon': {'label': 'Shield Neon',
                 'shape': 'shield',
                 'white_fill': '#d9ffef',
                 'black_fill': '#1ed760',
                 'black_stroke': '#0b5629',
                 'white_stroke': '#effff6'},
 'shield-obsidian': {'label': 'Shield Obsidian',
                     'shape': 'shield',
                     'white_fill': '#f1f1f1',
                     'black_fill': '#242424',
                     'black_stroke': '#080808',
                     'white_stroke': '#ffffff'},
 'shield-copper': {'label': 'Shield Copper',
                   'shape': 'shield',
                   'white_fill': '#f4dfd0',
                   'black_fill': '#9b5b3d',
                   'black_stroke': '#643421',
                   'white_stroke': '#fff8f2'},
 'shield-ice': {'label': 'Shield Ice',
                'shape': 'shield',
                'white_fill': '#eefaff',
                'black_fill': '#5f91b4',
                'black_stroke': '#335b78',
                'white_stroke': '#ffffff'},
 'shield-rose': {'label': 'Shield Rose',
                 'shape': 'shield',
                 'white_fill': '#f9e8ee',
                 'black_fill': '#a94f72',
                 'black_stroke': '#6f2e49',
                 'white_stroke': '#fff8fb'},
 'shield-aqua': {'label': 'Shield Aqua',
                 'shape': 'shield',
                 'white_fill': '#e2f9f7',
                 'black_fill': '#30878a',
                 'black_stroke': '#18575a',
                 'white_stroke': '#f6ffff'},
 'shield-amber': {'label': 'Shield Amber',
                  'shape': 'shield',
                  'white_fill': '#fff0c9',
                  'black_fill': '#a46c18',
                  'black_stroke': '#67420d',
                  'white_stroke': '#fffaf0'},
 'shield-lime': {'label': 'Shield Lime',
                 'shape': 'shield',
                 'white_fill': '#f1f7d8',
                 'black_fill': '#6f8f2f',
                 'black_stroke': '#425817',
                 'white_stroke': '#fbfff0'},
 'shield-crimson': {'label': 'Shield Crimson',
                    'shape': 'shield',
                    'white_fill': '#f8e4e4',
                    'black_fill': '#9f2333',
                    'black_stroke': '#651522',
                    'white_stroke': '#fff7f7'},
 'shield-silver': {'label': 'Shield Silver',
                   'shape': 'shield',
                   'white_fill': '#f3f4f5',
                   'black_fill': '#68747c',
                   'black_stroke': '#394147',
                   'white_stroke': '#ffffff'},
 'minimal': {'label': 'Minimal',
             'shape': 'minimal',
             'white_fill': '#f7f7f2',
             'black_fill': '#111111',
             'black_stroke': '#1a1a1a',
             'white_stroke': '#f7f7f2'},
 'minimal-gold': {'label': 'Minimal Gold',
                  'shape': 'minimal',
                  'white_fill': '#f5df9a',
                  'black_fill': '#8a5a14',
                  'black_stroke': '#5a3a0d',
                  'white_stroke': '#fff8dc'},
 'minimal-ruby': {'label': 'Minimal Ruby',
                  'shape': 'minimal',
                  'white_fill': '#f7e7e9',
                  'black_fill': '#8b2438',
                  'black_stroke': '#581421',
                  'white_stroke': '#fff8f8'},
 'minimal-emerald': {'label': 'Minimal Emerald',
                     'shape': 'minimal',
                     'white_fill': '#e9f7ef',
                     'black_fill': '#216b48',
                     'black_stroke': '#12402a',
                     'white_stroke': '#f6fff9'},
 'minimal-sapphire': {'label': 'Minimal Sapphire',
                      'shape': 'minimal',
                      'white_fill': '#e8eef9',
                      'black_fill': '#24558d',
                      'black_stroke': '#16345a',
                      'white_stroke': '#f7fbff'},
 'minimal-violet': {'label': 'Minimal Violet',
                    'shape': 'minimal',
                    'white_fill': '#f0e9f7',
                    'black_fill': '#70418e',
                    'black_stroke': '#44245a',
                    'white_stroke': '#fff8ff'},
 'minimal-neon': {'label': 'Minimal Neon',
                  'shape': 'minimal',
                  'white_fill': '#d9ffef',
                  'black_fill': '#1ed760',
                  'black_stroke': '#0b5629',
                  'white_stroke': '#effff6'},
 'minimal-obsidian': {'label': 'Minimal Obsidian',
                      'shape': 'minimal',
                      'white_fill': '#f1f1f1',
                      'black_fill': '#242424',
                      'black_stroke': '#080808',
                      'white_stroke': '#ffffff'},
 'minimal-copper': {'label': 'Minimal Copper',
                    'shape': 'minimal',
                    'white_fill': '#f4dfd0',
                    'black_fill': '#9b5b3d',
                    'black_stroke': '#643421',
                    'white_stroke': '#fff8f2'},
 'minimal-ice': {'label': 'Minimal Ice',
                 'shape': 'minimal',
                 'white_fill': '#eefaff',
                 'black_fill': '#5f91b4',
                 'black_stroke': '#335b78',
                 'white_stroke': '#ffffff'},
 'minimal-rose': {'label': 'Minimal Rose',
                  'shape': 'minimal',
                  'white_fill': '#f9e8ee',
                  'black_fill': '#a94f72',
                  'black_stroke': '#6f2e49',
                  'white_stroke': '#fff8fb'},
 'minimal-aqua': {'label': 'Minimal Aqua',
                  'shape': 'minimal',
                  'white_fill': '#e2f9f7',
                  'black_fill': '#30878a',
                  'black_stroke': '#18575a',
                  'white_stroke': '#f6ffff'},
 'minimal-amber': {'label': 'Minimal Amber',
                   'shape': 'minimal',
                   'white_fill': '#fff0c9',
                   'black_fill': '#a46c18',
                   'black_stroke': '#67420d',
                   'white_stroke': '#fffaf0'},
 'minimal-lime': {'label': 'Minimal Lime',
                  'shape': 'minimal',
                  'white_fill': '#f1f7d8',
                  'black_fill': '#6f8f2f',
                  'black_stroke': '#425817',
                  'white_stroke': '#fbfff0'},
 'minimal-crimson': {'label': 'Minimal Crimson',
                     'shape': 'minimal',
                     'white_fill': '#f8e4e4',
                     'black_fill': '#9f2333',
                     'black_stroke': '#651522',
                     'white_stroke': '#fff7f7'},
 'minimal-silver': {'label': 'Minimal Silver',
                    'shape': 'minimal',
                    'white_fill': '#f3f4f5',
                    'black_fill': '#68747c',
                    'black_stroke': '#394147',
                    'white_stroke': '#ffffff'}}

PIECE_DISPLAY_NAMES = {name: data["label"] for name, data in PIECE_SETS.items()}

NAME_COLORS = {
    "red": {"label": "Red", "discord_color": 0xC0392B},
    "yellow": {"label": "Yellow", "discord_color": 0xD4AC0D},
    "orange": {"label": "Orange", "discord_color": 0xD35400},
    "green": {"label": "Green", "discord_color": 0x239B56},
    "purple": {"label": "Purple", "discord_color": 0x8E44AD},
    "cyan": {"label": "Cyan", "discord_color": 0x17A2B8},
    "gold": {"label": "Gold", "discord_color": 0xB7950B},
    "gray": {"label": "Gray", "discord_color": 0x7F8C8D},
}

SHOP_COLOR_ROLE_PREFIX = "Shop Color • "
